# Generated by Django 4.1 on 2023-08-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("ville", models.CharField(max_length=100)),
                ("quartier", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "standing",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("moyen", "Moyen"),
                            ("haut", "Haut"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
