# Generated by Django 4.2.1 on 2023-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_alter_annonce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
